let project = new Project('Git Gold');
project.addAssets('Assets/**');
project.addSources('Sources');
project.addLibrary('Echoes');
project.addLibrary('hxbit');
project.addLibrary('slide');
project.addLibrary('nape-haxe4');
project.icon = 'Assets/icon.png';
project.windowOptions.width = 900;
project.windowOptions.height = 700;
resolve(project);
